import React from 'react'
import Users from './Users/Users'
import ChatBox from './ChatBox/ChatBox'
export const metadata = {
    title: "Chats",
    description: 'Generated by User',
}
const Chats = () => {
    return (
        <section className='flex h-[85vh]'>
            <div className='flex-0 w-[20%] min-h-full  bg-white border-r-2'>
                <Users />
            </div>
            <div className='flex-1 bg-[#E7EBEF] h-full'>
                <ChatBox />
            </div>
        </section>
    )
}

export default Chats