import React from 'react'
import UserInfo from './UserInfo'

export const metadata = {
    title: 'User Info',
    description: 'Generated by create next app',
}
const page = () => {
    return (
        <div>
            <UserInfo />
        </div>
    )
}

export default page