import React from 'react'
import AssignmentList from './myassignments/AssignmentList'
export const metadata = {
    title: 'Assigments',
    description: 'Generated by create next app',
}
const Assignments = () => {
    return (
        <div>
            <AssignmentList />
        </div>
    )
}

export default Assignments