import React from 'react'
import SkewComp from '@/components/SkewCom/SkewComp';
import Form from '../Form';
import { redirect } from 'next/navigation';
import { isJwt } from '@/utils/utils';


export const metadata = {
    title: 'Reset Password Link',
    description: 'Generated by create next app',
}


const ResetPassword = ({ params: { slug: token } }) => {
    if (!isJwt(token)) {
        redirect("/forgetpassword")
    }
    return (
        <div className='bg-main-app-primary relative w-[96%] sm:w-[55%] lg:w-[25%] text-white mx-auto p-4 rounded-md'>
            <SkewComp title="Reset Password" />
            <div className='pt-[30px]'>
                <Form token={token} />
            </div>
        </div>
    )
}

export default ResetPassword