
import React from 'react'
import { BsCopy } from "react-icons/bs";
import dynamic from 'next/dynamic';
const JoinedList = dynamic(() => import("./List/JoinedList"), { ssr: false })
const Form = dynamic(() => import('./Form/Form'), { ssr: false, })

export const metadata = {
    title: 'Meeting',
    description: 'Generated by create next app',
}

const Meeting = async () => {
    return (
        <>
            <Form />
            {/* join list  */}
            <section>
                {/* //list  */}
                <JoinedList />

            </section>
        </>
    )
}

export default Meeting