
import React from 'react'
import dynamic from 'next/dynamic';
import { courseList } from './services';
const JoinedList = dynamic(() => import("./List/JoinedList"), { ssr: false })
const Form = dynamic(() => import('./Form/Form'), { ssr: false, })

export const metadata = {
    title: 'Meeting',
    description: 'Generated by create next app',
}

const Meeting = async () => {
    const data = await courseList() || []
    return (
        <>
            <Form data={data} />
            {/* join list  */}
            <section>
                {/* //list  */}
                <JoinedList />
            </section>
        </>
    )
}

export default Meeting