import React from 'react'
import Form from './Form/Form'
import SkewComp from '@/components/SkewCom/SkewComp';

export const metadata = {
    title: 'Login',
    description: 'Generated by create next app',
}


const Login = () => {
    return (
        <div className='bg-main-app-primary relative w-[96%] sm:w-[55%] lg:w-[25%] text-white mx-auto p-4 rounded-md'>
            <SkewComp title="Student Login" />
            <div className='pt-[60px]'>
                <Form />
            </div>
        </div>
    )
}

export default Login