import React from 'react'
import dynamic from 'next/dynamic'
const Calendar = dynamic(() => import('./MyCalender/Calendar'), { ssr: false })
export const metadata = {
    title: 'My Attendance',
    description: 'Generated by create next app',
}
const MyAttendance = () => {
    return (
        <div>
            <Calendar />
        </div>
    )
}

export default MyAttendance