import React from 'react'
export const metadata = {
    title: 'Classes',
    description: 'Generated by create next app',
}
const Classes = () => {
    return (
        <div>Classes</div>
    )
}

export default Classes