import SkewComp from '@/components/SkewCom/SkewComp'
import React from 'react'
import Form from './Form/Form'


export const metadata = {
    title: 'Register',
    description: 'Generated by create next app',
}

const Register = () => {
    return (
        <div className='bg-main-app-primary relative w-[96%] sm:w-[55%] lg:w-[25%] text-white mx-auto p-4 rounded-md'>
            <SkewComp title="Student Register" />
            <div className='pt-[60px]'>
                <Form />
            </div>
        </div>
    )
}

export default Register