import React from 'react'

import AttendanceCalendar from './Data/AttendanceCalendar'
export const metadata = {
    title: 'Attendance',
    description: 'Generated by create next app',
}
const Attendance = () => {
    return (
        <section>
            <AttendanceCalendar />
        </section>
    )
}

export default Attendance